### ISSUE TITLE
chicken-slime  is not working in windows 7 x86-64

### ISSUE THREAD

**Issue by cneira** [nickg/swank-chicken#10]
Hi I have compiled chicken 4.10 in windows as stated in http://wiki.call-cc.org/compiling-chicken-on-windows-xp-with-mingw

Then installed chicken-swank following the instructions but I have this error with M-x chicken-slime

CHICKEN
(c) 2008-2015, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.10.0 (rev b259631)
windows-mingw32-x86-64 [ 64bit dload ptables ]
compiled 2015-08-04 on yves.more-magic.net (Linux)

; loading c:/chicken/lib/chicken/7/slime.import.so ...
; loading c:/chicken/lib/chicken/7/chicken.import.so ...
; loading c:/chicken/lib/chicken/7/irregex.import.so ...
; loading c:/chicken/lib/chicken/7/ports.import.so ...
; loading c:/chicken/lib/chicken/7/tcp.import.so ...
; loading c:/chicken/lib/chicken/7/posix.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-1.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-13.import.so ...
; loading c:/chicken/lib/chicken/7/symbol-utils.import.so ...
; loading c:/chicken/lib/chicken/7/data-structures.import.so ...
; loading c:/chicken/lib/chicken/7/type-checks.import.so ...
; loading c:/chicken/lib/chicken/7/type-errors.import.so ...
; loading c:/chicken/lib/chicken/7/foreign.import.so ...
; loading c:/chicken/lib/chicken/7/apropos.import.so ...
; loading c:/chicken/lib/chicken/7/extras.import.so ...
; loading c:/chicken/lib/chicken/7/csi.import.so ...
; loading c:/chicken/lib/chicken/7/miscmacros.import.so ...
; loading c:/chicken/lib/chicken/7/memoized-string.import.so ...
; loading c:/chicken/lib/chicken/7/lookup-table.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-69.import.so ...
; loading c:/chicken/lib/chicken/7/record-variants.import.so ...
; loading c:/chicken/lib/chicken/7/unicode-utils.import.so ...
; loading c:/chicken/lib/chicken/7/fmt.import.so ...
; loading c:/chicken/lib/chicken/7/chicken-doc.import.so ...
; loading c:/chicken/lib/chicken/7/matchable.import.so ...
; loading c:/chicken/lib/chicken/7/regex.import.so ...
; loading c:/chicken/lib/chicken/7/files.import.so ...
; loading c:/chicken/lib/chicken/7/utils.import.so ...
; loading c:/chicken/lib/chicken/7/chicken-doc-text.import.so ...
; loading c:/chicken/lib/chicken/7/fmt-unicode.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-4.import.so ...
; loading c:/chicken/lib/chicken/7/utf8-lolevel.import.so ...
; loading c:/chicken/lib/chicken/7/lolevel.import.so ...
; loading c:/chicken/lib/chicken/7/sxml-transforms.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-14.import.so ...
; loading c:/chicken/lib/chicken/7/trace.import.so ...
; loading c:/chicken/lib/chicken/7/advice.import.so ...
; loading c:/chicken/lib/chicken/7/slime.so ...
; loading c:/chicken/lib/chicken/7/symbol-utils.so ...
; loading c:/chicken/lib/chicken/7/type-checks.so ...
; loading c:/chicken/lib/chicken/7/type-errors.so ...
; loading c:/chicken/lib/chicken/7/apropos.so ...
; loading c:/chicken/lib/chicken/7/memoized-string.so ...
; loading c:/chicken/lib/chicken/7/lookup-table.so ...
; loading c:/chicken/lib/chicken/7/unicode-utils.so ...
; loading c:/chicken/lib/chicken/7/fmt.so ...
[panic] invalid encoded numeric literal - execution terminated

...more...
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<syntax>
<eval>
type-checks.scm:54: ##sys#require   <--

**Comment by dleslie** [comment]
Last that I checked, Chicken Slime's maintainer is no longer actively working on it. May I suggest that you try Geiser?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Carlos NeiraSent: Wednesday, November 18, 2015 5:45 AMTo: nickg/swank-chickenReply To: nickg/swank-chickenSubject: [swank-chicken] chicken-slime  is not working in windows 7 x86-64 (#10)Hi I have compiled chicken 4.10 in windows as stated in http://wiki.call-cc.org/compiling-chicken-on-windows-xp-with-mingw

Then installed chicken-swank following the instructions but I have this error with M-x chicken-slime

CHICKEN
(c) 2008-2015, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.10.0 (rev b259631)
windows-mingw32-x86-64 [ 64bit dload ptables ]
compiled 2015-08-04 on yves.more-magic.net (Linux)

; loading c:/chicken/lib/chicken/7/slime.import.so ...
; loading c:/chicken/lib/chicken/7/chicken.import.so ...
; loading c:/chicken/lib/chicken/7/irregex.import.so ...
; loading c:/chicken/lib/chicken/7/ports.import.so ...
; loading c:/chicken/lib/chicken/7/tcp.import.so ...
; loading c:/chicken/lib/chicken/7/posix.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-1.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-13.import.so ...
; loading c:/chicken/lib/chicken/7/symbol-utils.import.so ...
; loading c:/chicken/lib/chicken/7/data-structures.import.so ...
; loading c:/chicken/lib/chicken/7/type-checks.import.so ...
; loading c:/chicken/lib/chicken/7/type-errors.import.so ...
; loading c:/chicken/lib/chicken/7/foreign.import.so ...
; loading c:/chicken/lib/chicken/7/apropos.import.so ...
; loading c:/chicken/lib/chicken/7/extras.import.so ...
; loading c:/chicken/lib/chicken/7/csi.import.so ...
; loading c:/chicken/lib/chicken/7/miscmacros.import.so ...
; loading c:/chicken/lib/chicken/7/memoized-string.import.so ...
; loading c:/chicken/lib/chicken/7/lookup-table.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-69.import.so ...
; loading c:/chicken/lib/chicken/7/record-variants.import.so ...
; loading c:/chicken/lib/chicken/7/unicode-utils.import.so ...
; loading c:/chicken/lib/chicken/7/fmt.import.so ...
; loading c:/chicken/lib/chicken/7/chicken-doc.import.so ...
; loading c:/chicken/lib/chicken/7/matchable.import.so ...
; loading c:/chicken/lib/chicken/7/regex.import.so ...
; loading c:/chicken/lib/chicken/7/files.import.so ...
; loading c:/chicken/lib/chicken/7/utils.import.so ...
; loading c:/chicken/lib/chicken/7/chicken-doc-text.import.so ...
; loading c:/chicken/lib/chicken/7/fmt-unicode.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-4.import.so ...
; loading c:/chicken/lib/chicken/7/utf8-lolevel.import.so ...
; loading c:/chicken/lib/chicken/7/lolevel.import.so ...
; loading c:/chicken/lib/chicken/7/sxml-transforms.import.so ...
; loading c:/chicken/lib/chicken/7/srfi-14.import.so ...
; loading c:/chicken/lib/chicken/7/trace.import.so ...
; loading c:/chicken/lib/chicken/7/advice.import.so ...
; loading c:/chicken/lib/chicken/7/slime.so ...
; loading c:/chicken/lib/chicken/7/symbol-utils.so ...
; loading c:/chicken/lib/chicken/7/type-checks.so ...
; loading c:/chicken/lib/chicken/7/type-errors.so ...
; loading c:/chicken/lib/chicken/7/apropos.so ...
; loading c:/chicken/lib/chicken/7/memoized-string.so ...
; loading c:/chicken/lib/chicken/7/lookup-table.so ...
; loading c:/chicken/lib/chicken/7/unicode-utils.so ...
; loading c:/chicken/lib/chicken/7/fmt.so ...
[panic] invalid encoded numeric literal - execution terminated

...more...















type-checks.scm:54: ##sys#require   <--

—Reply to this email directly or view it on GitHub.

**Comment by cneira** [comment]
Thanks, I'll check geiser or try to debug this.
Bests

**Comment by cneira** [comment]
This is needed to fix it, seems to be related to applyhack 
http://nongnu.13855.n7.nabble.com/package-fmt-crash-on-Windows-7-64-bits-td193470.html
