### ISSUE TITLE
Port to CHICKEN 5

### ISSUE THREAD

**Issue by matiaslina** [nickg/swank-chicken#12]
Hi! 

I've ported this egg to chicken 5 following the [porting guide](http://wiki.call-cc.org/porting-c4-to-c5#re-packaging-eggs). I've tested it with the following version and it seems to be working fine

```
% chicken -version
CHICKEN
(c) 2008-2021, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 5.3.0 (rev e31bbee5)
linux-unix-gnu-x86-64 [ 64bit dload ptables ]
```

```
slime version: 20240605.1810
```

Couple of things before making a pull request:

* I dropped support for chicken 4. Is that OK? I could use [chicken-version](http://wiki.call-cc.org/man/5/Module%20(chicken%20platform)#chicken-version) to maintain compatibility, but I don't know if chicken 4 is deprecated or not.
* I still don't know how to install `chicken-slime.el` into the chicken install directory like https://github.com/nickg/swank-chicken/blob/master/slime.setup#L12. I think this could be done with [data](http://wiki.call-cc.org/man/5/Egg%20specification%20format#data) from the `component` part in the `.egg` file. Will need more time with this.

Repo/Branch: https://github.com/matiaslina/swank-chicken/tree/chicken-5

**Comment by nickg** [comment]
> I dropped support for chicken 4. Is that OK? I could use [chicken-version](http://wiki.call-cc.org/man/5/Module%20(chicken%20platform)#chicken-version) to maintain compatibility, but I don't know if chicken 4 is deprecated or not.

I'm fine with this. To be honest I haven't used this in quite a while, but I'll happy merge a PR if you send one.
