### ISSUE TITLE
error installing..

### ISSUE THREAD

**Issue by JoePython1** [nickg/swank-chicken#9]
OS - Ubuntu 14.04
Version 4.9.0.1 (stability/4.9.0) (rev 8b3189b)
linux-unix-gnu-x86-64 [ 64bit manyargs dload ptables ]
bootstrapped 2014-06-07

sudo chicken-install 
retrieving ...
checking platform for `slime' ...
checking dependencies for `slime' ...
install order:
("slime")
installing slime: ...
changing current directory to .
  '/usr/local/bin/csi' -bnq -setup-mode -e "(require-library setup-api)" -e "(import setup-api)" -e "(setup-error-handling)" -e "(extension-name-and-version '(\"slime\" \"\"))" 'slime.setup'
  '/usr/local/bin/csc' -feature compiling-extension -setup-mode    -s -O2 -d1 slime.scm -j slime

Syntax error: (swank-chicken.scm:632) in `define' - not enough arguments

	(define (swank-trace-dialog:report-partial-tree fetch-key))

	Expansion history:

	<syntax>	  (define (swank-trace-dialog:dialog-untrace symbol) (quote (:ok nil)))
	<syntax>	  (##core#set! swank-trace-dialog:dialog-untrace (##core#lambda (symbol) (quote (:ok nil))))
	<syntax>	  (##core#lambda (symbol) (quote (:ok nil)))
	<syntax>	  (##core#begin (##core#quote (:ok nil)))
	<syntax>	  (##core#quote (:ok nil))
	<syntax>	  (define (swank-trace-dialog:report-specs) (quote (:ok nil)))
	<syntax>	  (##core#set! swank-trace-dialog:report-specs (##core#lambda () (quote (:ok nil))))
	<syntax>	  (##core#lambda () (quote (:ok nil)))
	<syntax>	  (##core#begin (##core#quote (:ok nil)))
	<syntax>	  (##core#quote (:ok nil))
	<syntax>	  (define (swank-trace-dialog:report-total) (quote (:ok 0)))
	<syntax>	  (##core#set! swank-trace-dialog:report-total (##core#lambda () (quote (:ok 0))))
	<syntax>	  (##core#lambda () (quote (:ok 0)))
	<syntax>	  (##core#begin (##core#quote (:ok 0)))
	<syntax>	  (##core#quote (:ok 0))
	<syntax>	  (define (swank-trace-dialog:report-partial-tree fetch-key))	<--

Error: shell command terminated with non-zero exit status 17920: '/usr/local/bin/chicken' 'slime.scm' -output-file 'slime.c' -dynamic -feature chicken-compile-shared -feature compiling-extension -setup-mode -optimize-level 2 -debug-level 1 -emit-import-library slime

Error: shell command failed with nonzero exit status 256:

  '/usr/local/bin/csc' -feature compiling-extension -setup-mode    -s -O2 -d1 slime.scm -j slime

Error: shell command terminated with nonzero exit code
17920
"'/usr/local/bin/csi' -bnq -setup-mode -e \"(require-library setup-api)\" -e \"(...

**Comment by nickg** [comment]
Should be fixed now
